# Generated by Django 5.0.3 on 2024-04-06 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_customuser_bio_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postImage',
            field=models.ImageField(default='', upload_to='post_img'),
        ),
    ]
